package lesson5

import lesson5.impl.GraphBuilder
import kotlin.test.assertEquals
import kotlin.test.assertTrue

abstract class AbstractGraphTests {

    private fun Graph.Edge.isNeighbour(other: Graph.Edge): Boolean {
        return begin == other.begin || end == other.end || begin == other.end || end == other.begin
    }

    private fun List<Graph.Edge>.assert(shouldExist: Boolean, graph: Graph) {
        val edges = graph.edges
        if (shouldExist) {
            assertEquals(edges.size, size, "Euler loop should traverse all edges")
        } else {
            assertTrue(isEmpty(), "Euler loop should not exist")
        }
        for (edge in this) {
            assertTrue(edge in edges, "Edge $edge is not inside graph")
        }
        for (i in 0 until size - 1) {
            assertTrue(this[i].isNeighbour(this[i + 1]), "Edges ${this[i]} & ${this[i + 1]} are not incident")
        }
        if (size > 1) {
            assertTrue(this[0].isNeighbour(this[size - 1]), "Edges ${this[0]} & ${this[size - 1]} are not incident")
        }
    }

    fun findEulerLoop(findEulerLoop: Graph.() -> List<Graph.Edge>) {
        val emptyGraph = GraphBuilder().build()
        val emptyLoop = emptyGraph.findEulerLoop()
        assertTrue(emptyLoop.isEmpty(), "Euler loop should be empty for the empty graph")
        val simpleGraph = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            addConnection(a, b)
        }.build()
        val simpleLoop = simpleGraph.findEulerLoop()
        simpleLoop.assert(shouldExist = false, graph = simpleGraph)
        val unconnected = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            addConnection(a, b)
            addConnection(c, d)
        }.build()
        val unconnectedLoop = unconnected.findEulerLoop()
        unconnectedLoop.assert(shouldExist = false, graph = unconnected)
        val graph = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(a, c)
        }.build()
        val loop = graph.findEulerLoop()
        loop.assert(shouldExist = true, graph = graph)
        val graph2 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            //
            //       g -- h
            //       |    |
            //  a -- b -- c -- d
            //  |    |    |    |
            //  e    f -- i    |
            //  |              |
            //  j ------------ k
            //
            // ab bc cd
            //
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(a, e)
            addConnection(d, k)
            addConnection(e, j)
            addConnection(j, k)
            addConnection(b, f)
            addConnection(c, i)
            addConnection(f, i)
            addConnection(b, g)
            addConnection(g, h)
            addConnection(h, c)
        }.build()
        val loop2 = graph2.findEulerLoop()
        loop2.assert(shouldExist = true, graph = graph2)
        // Seven bridges of Koenigsberg
        //    A1 -- A2 ---
        //    |      |    |
        //    B1 -- B2 -- C
        //    |     |     |
        //    D1 -- D2 ---
        val graph3 = GraphBuilder().apply {
            val a1 = addVertex("A1")
            val a2 = addVertex("A2")
            val b1 = addVertex("B1")
            val b2 = addVertex("B2")
            val c = addVertex("C")
            val d1 = addVertex("D1")
            val d2 = addVertex("D2")
            addConnection(a1, a2)
            addConnection(b1, b2)
            addConnection(d1, d2)
            addConnection(a1, b1)
            addConnection(b1, d1)
            addConnection(a2, b2)
            addConnection(b2, d2)
            addConnection(a2, c)
            addConnection(b2, c)
            addConnection(d2, c)
        }.build()
        val loop3 = graph3.findEulerLoop()
        loop3.assert(shouldExist = false, graph = graph3)

        //
        //  a -- b -- c -- d
        //  |              |
        //  e -- f -- g -- h
        //  |    |    |    |
        //  i -- j    k -- l
        //
        val customGraph1 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, h)
            addConnection(h, g)
            addConnection(g, f)
            addConnection(f, e)
            addConnection(e, a)
            addConnection(h, l)
            addConnection(l, k)
            addConnection(k, g)
            addConnection(f, j)
            addConnection(j, i)
            addConnection(i, e)
        }.build()
        val customLoop1 = customGraph1.findEulerLoop()
        customLoop1.assert(shouldExist = false, graph = customGraph1)

        //
        //          g -- h -- i -- j
        //          |              |
        //  <- a -- b -- c -- d -- e -- f ->
        //          |              |
        //          k ------------ l
        //
        val customGraph2 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, e)
            addConnection(e, f)
            addConnection(f, a)
            addConnection(b, g)
            addConnection(g, h)
            addConnection(h, i)
            addConnection(i, j)
            addConnection(j, e)
            addConnection(b, k)
            addConnection(k, l)
            addConnection(l, e)
        }.build()
        val customLoop2 = customGraph2.findEulerLoop()
        customLoop2.assert(shouldExist = true, graph = customGraph2)

        //
        //     |    |    |
        //  -- a -- b -- c --
        //     |    |    |
        //  -- d -- e -- f --
        //     |    |    |
        //  -- g -- h -- i --
        //     |    |    |
        //
        val customGraph3 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, a)
            addConnection(d, e)
            addConnection(e, f)
            addConnection(f, d)
            addConnection(g, h)
            addConnection(h, i)
            addConnection(i, g)
            addConnection(a, d)
            addConnection(d, g)
            addConnection(g, a)
            addConnection(b, e)
            addConnection(e, h)
            addConnection(h, b)
            addConnection(c, f)
            addConnection(f, i)
            addConnection(i, c)
        }.build()
        val customLoop3 = customGraph3.findEulerLoop()
        customLoop3.assert(shouldExist = true, graph = customGraph3)
    }

    fun minimumSpanningTree(minimumSpanningTree: Graph.() -> Graph) {
        val emptyGraph = GraphBuilder().build()
        assertTrue(emptyGraph.minimumSpanningTree().edges.isEmpty())
        val graph = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(a, c)
        }.build()
        val tree = graph.minimumSpanningTree()
        assertEquals(2, tree.edges.size)
        assertEquals(2, tree.findBridges().size)
        val graph2 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(a, e)
            addConnection(d, k)
            addConnection(e, j)
            addConnection(j, k)
            addConnection(b, f)
            addConnection(c, i)
            addConnection(f, i)
            addConnection(b, g)
            addConnection(g, h)
            addConnection(h, c)
        }.build()
        val tree2 = graph2.minimumSpanningTree()
        assertEquals(10, tree2.edges.size)
        assertEquals(10, tree2.findBridges().size)
        // Cross
        val graph3 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            addConnection(a, e)
            addConnection(b, e)
            addConnection(c, e)
            addConnection(d, e)
        }.build()
        val tree3 = graph3.minimumSpanningTree()
        assertEquals(4, tree3.edges.size)
        assertEquals(4, tree3.findBridges().size)

        val customGraph1 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, h)
            addConnection(h, g)
            addConnection(g, f)
            addConnection(f, e)
            addConnection(e, a)
            addConnection(h, l)
            addConnection(l, k)
            addConnection(k, g)
            addConnection(f, j)
            addConnection(j, i)
            addConnection(i, e)
        }.build()
        val customTree1 = customGraph1.minimumSpanningTree()
        assertEquals(11, customTree1.edges.size)
        assertEquals(11, customTree1.findBridges().size)

        val customGraph2 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, e)
            addConnection(e, f)
            addConnection(f, a)
            addConnection(b, g)
            addConnection(g, h)
            addConnection(h, i)
            addConnection(i, j)
            addConnection(j, e)
            addConnection(b, k)
            addConnection(k, l)
            addConnection(l, e)
        }.build()
        val customTree2 = customGraph2.minimumSpanningTree()
        assertEquals(11, customTree2.edges.size)
        assertEquals(11, customTree2.findBridges().size)

        val customGraph3 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, a)
            addConnection(d, e)
            addConnection(e, f)
            addConnection(f, d)
            addConnection(g, h)
            addConnection(h, i)
            addConnection(i, g)
            addConnection(a, d)
            addConnection(d, g)
            addConnection(g, a)
            addConnection(b, e)
            addConnection(e, h)
            addConnection(h, b)
            addConnection(c, f)
            addConnection(f, i)
            addConnection(i, c)
        }.build()
        val customTree3 = customGraph3.minimumSpanningTree()
        assertEquals(8, customTree3.edges.size)
        assertEquals(8, customTree3.findBridges().size)
    }

    fun largestIndependentVertexSet(largestIndependentVertexSet: Graph.() -> Set<Graph.Vertex>) {
        val emptyGraph = GraphBuilder().build()
        assertTrue(emptyGraph.largestIndependentVertexSet().isEmpty())
        val simpleGraph = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            addConnection(a, b)
        }.build()
        assertEquals(
            setOf(simpleGraph["A"]),
            simpleGraph.largestIndependentVertexSet()
        )
        val unconnected = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            addConnection(a, b)
            addConnection(c, d)
            addConnection(d, e)
        }.build()
        assertEquals(
            setOf(unconnected["A"], unconnected["C"], unconnected["E"]),
            unconnected.largestIndependentVertexSet()
        )
        val graph = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            addConnection(a, b)
            addConnection(a, c)
            addConnection(b, d)
            addConnection(c, e)
            addConnection(c, f)
            addConnection(b, g)
            addConnection(d, i)
            addConnection(g, h)
            addConnection(h, j)
        }.build()
        assertEquals(
            setOf(graph["A"], graph["D"], graph["E"], graph["F"], graph["G"], graph["J"]),
            graph.largestIndependentVertexSet()
        )
        val cross = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            addConnection(a, e)
            addConnection(b, e)
            addConnection(c, e)
            addConnection(d, e)
        }.build()
        assertEquals(
            setOf(cross["A"], cross["B"], cross["C"], cross["D"]),
            cross.largestIndependentVertexSet()
        )

        val customGraph1 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, h)
            addConnection(h, g)
            addConnection(g, f)
            addConnection(f, e)
            addConnection(e, a)
            addConnection(h, l)
            addConnection(l, k)
            addConnection(k, g)
            addConnection(f, j)
            addConnection(i, e)
        }.build()
        assertEquals(
            setOf(customGraph1["A"], customGraph1["C"], customGraph1["E"], customGraph1["G"],
                customGraph1["I"], customGraph1["J"], customGraph1["L"]),
            customGraph1.largestIndependentVertexSet()
        )

        val customGraph2 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, e)
            addConnection(e, f)
            addConnection(f, a)
            addConnection(b, g)
            addConnection(g, h)
            addConnection(h, i)
            addConnection(i, j)
            addConnection(j, e)
            addConnection(b, k)
            addConnection(k, l)
            addConnection(l, e)
        }.build()
        assertEquals(
            setOf(customGraph2["A"], customGraph2["C"], customGraph2["E"],
                customGraph2["G"], customGraph2["I"],customGraph2["K"]),
            customGraph2.largestIndependentVertexSet()
        )

        val customGraph3 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
        }.build()
        assertEquals(
            setOf(customGraph3["A"], customGraph3["B"], customGraph3["C"], customGraph3["D"],
                customGraph3["E"], customGraph3["F"], customGraph3["G"], customGraph3["H"], customGraph3["I"]),
            customGraph3.largestIndependentVertexSet()
        )
    }

    fun longestSimplePath(longestSimplePath: Graph.() -> Path) {
        val emptyGraph = GraphBuilder().build()
        assertEquals(0, emptyGraph.longestSimplePath().length)

        val unconnected = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            addConnection(a, b)
            addConnection(c, d)
            addConnection(d, e)
        }.build()
        val longestUnconnectedPath = unconnected.longestSimplePath()
        assertEquals(2, longestUnconnectedPath.length)

        val graph = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(a, c)
        }.build()
        val longestPath = graph.longestSimplePath()
        assertEquals(2, longestPath.length)

        val graph2 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(a, e)
            addConnection(d, k)
            addConnection(e, j)
            addConnection(j, k)
            addConnection(b, f)
            addConnection(c, i)
            addConnection(f, i)
            addConnection(b, g)
            addConnection(g, h)
            addConnection(h, c)
        }.build()
        val longestPath2 = graph2.longestSimplePath()
        assertEquals(10, longestPath2.length)
        // Seven bridges of Koenigsberg
        //    A1 -- A2 ---
        //    |      |    |
        //    B1 -- B2 -- C
        //    |     |     |
        //    D1 -- D2 ---
        val graph3 = GraphBuilder().apply {
            val a1 = addVertex("A1")
            val a2 = addVertex("A2")
            val b1 = addVertex("B1")
            val b2 = addVertex("B2")
            val c = addVertex("C")
            val d1 = addVertex("D1")
            val d2 = addVertex("D2")
            addConnection(a1, a2)
            addConnection(b1, b2)
            addConnection(d1, d2)
            addConnection(a1, b1)
            addConnection(b1, d1)
            addConnection(a2, b2)
            addConnection(b2, d2)
            addConnection(a2, c)
            addConnection(b2, c)
            addConnection(d2, c)
        }.build()
        val longestPath3 = graph3.longestSimplePath()
        assertEquals(6, longestPath3.length)

        val customGraph1 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, h)
            addConnection(h, g)
            addConnection(g, f)
            addConnection(f, e)
            addConnection(e, a)
            addConnection(h, l)
            addConnection(l, k)
            addConnection(k, g)
            addConnection(f, j)
            addConnection(j, i)
            addConnection(i, e)
        }.build()
        val customLongest1 = customGraph1.longestSimplePath()
        assertEquals(11, customLongest1.length)

        val customGraph2 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            val j = addVertex("J")
            val k = addVertex("K")
            val l = addVertex("L")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, d)
            addConnection(d, e)
            addConnection(e, f)
            addConnection(f, a)
            addConnection(b, g)
            addConnection(g, h)
            addConnection(h, i)
            addConnection(i, j)
            addConnection(j, e)
            addConnection(b, k)
            addConnection(k, l)
            addConnection(l, e)
        }.build()
        val customLongest2 = customGraph2.longestSimplePath()
        assertEquals(9, customLongest2.length)

        val customGraph3 = GraphBuilder().apply {
            val a = addVertex("A")
            val b = addVertex("B")
            val c = addVertex("C")
            val d = addVertex("D")
            val e = addVertex("E")
            val f = addVertex("F")
            val g = addVertex("G")
            val h = addVertex("H")
            val i = addVertex("I")
            addConnection(a, b)
            addConnection(b, c)
            addConnection(c, a)
            addConnection(d, e)
            addConnection(e, f)
            addConnection(f, d)
            addConnection(g, h)
            addConnection(h, i)
            addConnection(i, g)
            addConnection(a, d)
            addConnection(d, g)
            addConnection(g, a)
            addConnection(b, e)
            addConnection(e, h)
            addConnection(h, b)
            addConnection(c, f)
            addConnection(f, i)
            addConnection(i, c)
        }.build()
        val customLongest3 = customGraph3.longestSimplePath()
        assertEquals(8, customLongest3.length)
    }

}